"""initial control plane schema

Hand-authored rather than autogenerated: this environment had no live PostgreSQL instance
available at authoring time (Docker daemon was not running), and autogenerate requires a real
connection to diff against. The DDL below mirrors src/hermes_rpt/**/models.py exactly. Before
this is considered final it must be applied to a real PostgreSQL instance (`make up && make
migrate`) and checked against `alembic check` / a fresh `--autogenerate` diff to catch any
hand-authoring mistakes — see TASKS.md Phase 2.

Revision ID: d9d76db9f705
Revises:
Create Date: 2026-07-27 10:56:47.086235

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9d76db9f705"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def _timestamp_columns() -> tuple[sa.Column, sa.Column]:
    """Fresh Column instances per call — a Column object can only belong to one Table."""
    return (
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_tenants_slug", "tenants", ["slug"])

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("description", sa.String(500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_roles_name", "roles", ["name"])

    op.create_table(
        "user_tenant_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint(
            "tenant_id", "user_id", "role_id", name="uq_user_tenant_membership_role"
        ),
    )
    op.create_index(
        "ix_user_tenant_memberships_tenant_id", "user_tenant_memberships", ["tenant_id"]
    )
    op.create_index("ix_user_tenant_memberships_user_id", "user_tenant_memberships", ["user_id"])

    op.create_table(
        "data_access_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.String(1000), nullable=False),
        sa.Column("policy_document", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_data_access_policies_tenant_id", "data_access_policies", ["tenant_id"])

    op.create_table(
        "data_usage_consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("consent_type", sa.String(100), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("notes", sa.String(1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by_user_id"], ["users.id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_data_usage_consents_tenant_id", "data_usage_consents", ["tenant_id"])

    op.create_table(
        "database_credential_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(100), nullable=False),
        sa.Column("reference_key", sa.String(500), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_database_credential_references_tenant_id",
        "database_credential_references",
        ["tenant_id"],
    )

    op.create_table(
        "customer_database_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("engine", sa.String(20), nullable=False),
        sa.Column("host", sa.String(255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(200), nullable=False),
        sa.Column("username", sa.String(200), nullable=False),
        sa.Column("tls_mode", sa.String(50), nullable=False),
        sa.Column("credential_reference_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(30), nullable=False),
        sa.Column("schema_allowlist", sa.JSON(), nullable=False),
        sa.Column("table_allowlist", sa.JSON(), nullable=False),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(1000), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["credential_reference_id"], ["database_credential_references.id"], ondelete="RESTRICT"
        ),
    )
    op.create_index(
        "ix_customer_database_connections_tenant_id", "customer_database_connections", ["tenant_id"]
    )

    op.create_table(
        "schema_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("schema_fingerprint", sa.String(128), nullable=True),
        sa.Column("metadata_document", sa.JSON(), nullable=False),
        sa.Column("table_fingerprints", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["customer_database_connections.id"], ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "tenant_id", "connection_id", "sequence_number", name="uq_schema_snapshot_sequence"
        ),
    )
    op.create_index("ix_schema_snapshots_tenant_id", "schema_snapshots", ["tenant_id"])
    op.create_index("ix_schema_snapshots_connection_id", "schema_snapshots", ["connection_id"])

    op.create_table(
        "schema_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("entity_name", sa.String(200), nullable=False),
        sa.Column("schema_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("ontology_version", sa.String(50), nullable=False),
        sa.Column("state", sa.String(30), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column("suspended_due_to_drift", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["schema_snapshot_id"], ["schema_snapshots.id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_schema_mappings_tenant_id", "schema_mappings", ["tenant_id"])

    op.create_table(
        "mapping_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("schema_mapping_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("mapping_document", sa.JSON(), nullable=False),
        sa.Column("is_ai_suggested", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("explanation", sa.String(2000), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schema_mapping_id"], ["schema_mappings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.UniqueConstraint(
            "tenant_id", "schema_mapping_id", "version_number", name="uq_mapping_version_number"
        ),
    )
    op.create_index("ix_mapping_versions_tenant_id", "mapping_versions", ["tenant_id"])

    op.create_foreign_key(
        "fk_schema_mapping_active_version",
        "schema_mappings",
        "mapping_versions",
        ["active_version_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "prediction_task_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("task_key", sa.String(100), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.String(2000), nullable=False),
        sa.Column("feature_contract_version", sa.String(50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_key"),
    )
    op.create_index(
        "ix_prediction_task_definitions_task_key", "prediction_task_definitions", ["task_key"]
    )

    op.create_table(
        "prediction_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("task_definition_id", sa.Uuid(), nullable=False),
        sa.Column("business_reference", sa.String(200), nullable=False),
        sa.Column("prediction_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("idempotency_key", sa.String(200), nullable=True),
        sa.Column("requested_by_principal_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.String(128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_definition_id"], ["prediction_task_definitions.id"], ondelete="RESTRICT"
        ),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_prediction_request_idempotency"
        ),
    )
    op.create_index("ix_prediction_requests_tenant_id", "prediction_requests", ["tenant_id"])

    op.create_table(
        "model_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("version_label", sa.String(50), nullable=False),
        sa.Column("task_definition_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(20), nullable=False),
        sa.Column("artifact_uri", sa.String(1000), nullable=False),
        sa.Column("artifact_checksum", sa.String(128), nullable=False),
        sa.Column("mlflow_run_id", sa.String(100), nullable=True),
        sa.Column("ontology_version", sa.String(50), nullable=False),
        sa.Column("feature_contract_version", sa.String(50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["task_definition_id"], ["prediction_task_definitions.id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_model_versions_tenant_id", "model_versions", ["tenant_id"])

    op.create_table(
        "tenant_model_adapters",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("base_model_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("version_label", sa.String(50), nullable=False),
        sa.Column("stage", sa.String(20), nullable=False),
        sa.Column("artifact_uri", sa.String(1000), nullable=False),
        sa.Column("artifact_checksum", sa.String(128), nullable=False),
        sa.Column("ontology_version", sa.String(50), nullable=False),
        sa.Column("feature_contract_version", sa.String(50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["base_model_version_id"], ["model_versions.id"], ondelete="RESTRICT"
        ),
    )
    op.create_index("ix_tenant_model_adapters_tenant_id", "tenant_model_adapters", ["tenant_id"])

    op.create_table(
        "prediction_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("prediction_request_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_model_adapter_id", sa.Uuid(), nullable=True),
        sa.Column("mapping_version_id", sa.Uuid(), nullable=False),
        sa.Column("feature_version", sa.String(50), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("explanations", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prediction_request_id"], ["prediction_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["model_version_id"], ["model_versions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["tenant_model_adapter_id"], ["tenant_model_adapters.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["mapping_version_id"], ["mapping_versions.id"], ondelete="RESTRICT"
        ),
        sa.UniqueConstraint("prediction_request_id"),
    )
    op.create_index("ix_prediction_results_tenant_id", "prediction_results", ["tenant_id"])

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        *_timestamp_columns(),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("principal_id", sa.Uuid(), nullable=True),
        sa.Column("principal_type", sa.String(30), nullable=False),
        sa.Column("action", sa.String(200), nullable=False),
        sa.Column("resource_type", sa.String(100), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(20), nullable=False),
        sa.Column("correlation_id", sa.String(128), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_audit_events_action", "audit_events", ["action"])
    op.create_index("ix_audit_events_tenant_created", "audit_events", ["tenant_id", "created_at"])


def downgrade() -> None:
    op.drop_table("audit_events")
    op.drop_table("prediction_results")
    op.drop_table("tenant_model_adapters")
    op.drop_table("model_versions")
    op.drop_table("prediction_requests")
    op.drop_table("prediction_task_definitions")
    op.drop_constraint("fk_schema_mapping_active_version", "schema_mappings", type_="foreignkey")
    op.drop_table("mapping_versions")
    op.drop_table("schema_mappings")
    op.drop_table("schema_snapshots")
    op.drop_table("customer_database_connections")
    op.drop_table("database_credential_references")
    op.drop_table("data_usage_consents")
    op.drop_table("data_access_policies")
    op.drop_table("user_tenant_memberships")
    op.drop_table("roles")
    op.drop_table("users")
    op.drop_table("tenants")
